ALTER TABLE tenant.company_license
    ADD COLUMN IF NOT EXISTS enabled_features text[] NOT NULL DEFAULT '{}';

UPDATE tenant.company_license
SET plan_code = CASE upper(plan_code)
    WHEN 'POS' THEN 'POS'
    WHEN 'FULL' THEN 'FULL'
    WHEN 'CUSTOM' THEN 'CUSTOM'
    ELSE 'CUSTOM'
END;

UPDATE tenant.company_license
SET enabled_modules = ARRAY['COMPANY','THIRDPARTY','INVENTORY','BILLING','ACCOUNTING','PAYROLL','REPORTS','CATALOGS','AUDIT','USERS'],
    enabled_features = ARRAY[
        'COMPANY_BASIC','BRANDING_BASIC','CUSTOMERS','SUPPLIERS','PRODUCTS_SERVICES','INVENTORY_BASIC',
        'INVENTORY_ADVANCED','POS_SALES','ELECTRONIC_BILLING','SALES_REGISTRY','FISCAL_SETTINGS_BASIC',
        'FISCAL_DOCUMENTS_BASIC','REPORTS_BASIC','CATALOGS_OPERATING','AUDIT_BASIC','USERS_BASIC',
        'OPERATIONAL_PIN','ACCOUNTING_CORE','ACCOUNTING_ADVANCED','PURCHASES','EXPENSES','RECEIVABLES',
        'FISCAL_RULES_ADVANCED','PAYROLL','REPORTS_ASYNC','AUDIT_ADVANCED','USERS_ADVANCED'
    ]
WHERE plan_code = 'FULL';

UPDATE tenant.company_license
SET enabled_modules = ARRAY['COMPANY','THIRDPARTY','INVENTORY','BILLING','REPORTS','CATALOGS','AUDIT','USERS'],
    enabled_features = ARRAY[
        'COMPANY_BASIC','BRANDING_BASIC','CUSTOMERS','PRODUCTS_SERVICES','INVENTORY_BASIC','POS_SALES',
        'ELECTRONIC_BILLING','SALES_REGISTRY','FISCAL_SETTINGS_BASIC','FISCAL_DOCUMENTS_BASIC',
        'REPORTS_BASIC','CATALOGS_OPERATING','AUDIT_BASIC','USERS_BASIC','OPERATIONAL_PIN','ACCOUNTING_CORE'
    ]
WHERE plan_code = 'POS';

UPDATE tenant.company_license
SET enabled_features = ARRAY(
    SELECT DISTINCT feature
    FROM unnest(
        ARRAY[]::text[]
        || CASE WHEN 'COMPANY' = ANY(enabled_modules) THEN ARRAY['COMPANY_BASIC','BRANDING_BASIC'] ELSE ARRAY[]::text[] END
        || CASE WHEN 'THIRDPARTY' = ANY(enabled_modules) THEN ARRAY['CUSTOMERS','SUPPLIERS'] ELSE ARRAY[]::text[] END
        || CASE WHEN 'INVENTORY' = ANY(enabled_modules) THEN ARRAY['PRODUCTS_SERVICES','INVENTORY_BASIC','INVENTORY_ADVANCED'] ELSE ARRAY[]::text[] END
        || CASE WHEN 'BILLING' = ANY(enabled_modules) THEN ARRAY['POS_SALES','ELECTRONIC_BILLING','SALES_REGISTRY','FISCAL_SETTINGS_BASIC','FISCAL_DOCUMENTS_BASIC','OPERATIONAL_PIN','ACCOUNTING_CORE'] ELSE ARRAY[]::text[] END
        || CASE WHEN 'ACCOUNTING' = ANY(enabled_modules) THEN ARRAY['ACCOUNTING_CORE','ACCOUNTING_ADVANCED','PURCHASES','EXPENSES','RECEIVABLES','FISCAL_RULES_ADVANCED'] ELSE ARRAY[]::text[] END
        || CASE WHEN 'PAYROLL' = ANY(enabled_modules) THEN ARRAY['PAYROLL'] ELSE ARRAY[]::text[] END
        || CASE WHEN 'REPORTS' = ANY(enabled_modules) THEN ARRAY['REPORTS_BASIC','REPORTS_ASYNC'] ELSE ARRAY[]::text[] END
        || CASE WHEN 'CATALOGS' = ANY(enabled_modules) THEN ARRAY['CATALOGS_OPERATING'] ELSE ARRAY[]::text[] END
        || CASE WHEN 'AUDIT' = ANY(enabled_modules) THEN ARRAY['AUDIT_BASIC','AUDIT_ADVANCED'] ELSE ARRAY[]::text[] END
        || CASE WHEN 'USERS' = ANY(enabled_modules) THEN ARRAY['USERS_BASIC','USERS_ADVANCED'] ELSE ARRAY[]::text[] END
    ) AS feature
)
WHERE plan_code = 'CUSTOM' AND cardinality(enabled_features) = 0;
