sonar.projectKey=nexofiscal
sonar.projectName=NexoFiscal
sonar.projectVersion=0.0.1-SNAPSHOT
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

sonar.sources=services,apps/facturaelectronica-web/src,infra
sonar.test.inclusions=services/**/src/test/**,apps/facturaelectronica-web/src/**/*.test.js,apps/facturaelectronica-web/src/**/*.test.jsx

sonar.exclusions=**/target/**,**/dist/**,**/node_modules/**,**/coverage/**,**/.scannerwork/**,**/.sonar/**,**/*.pdf,**/*.docx,**/package-lock.json,services/**/src/test/**,apps/facturaelectronica-web/src/**/*.test.js,apps/facturaelectronica-web/src/**/*.test.jsx
sonar.coverage.exclusions=**/*Application.java,**/*ApplicationTests.java,**/src/test/**,**/*.config.js,**/vite.config.js

sonar.java.binaries=services/**/target/classes
sonar.java.test.binaries=services/**/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=services/**/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=apps/facturaelectronica-web/coverage/lcov.info

sonar.qualitygate.wait=true
