CREATE SCHEMA IF NOT EXISTS thirdparty;

CREATE TABLE thirdparty.cliente (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID,
    nombre VARCHAR(100) NOT NULL,
    id_tipo_documento BIGINT NOT NULL,
    numero_documento BIGINT NOT NULL,
    digito_verificacion INTEGER,
    direccion VARCHAR(150),
    telefono VARCHAR(15),
    correo_electronico VARCHAR(100),
    tipo_cliente VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL,
    CONSTRAINT uk_cliente_company_document UNIQUE (company_id, id_tipo_documento, numero_documento)
);

CREATE TABLE thirdparty.proveedor (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID,
    nombre VARCHAR(100) NOT NULL,
    id_tipo_documento BIGINT NOT NULL,
    numero_documento BIGINT NOT NULL,
    digito_verificacion INTEGER,
    direccion VARCHAR(150),
    telefono VARCHAR(15),
    correo_electronico VARCHAR(100),
    activo BOOLEAN NOT NULL,
    CONSTRAINT uk_proveedor_company_document UNIQUE (company_id, id_tipo_documento, numero_documento)
);

CREATE INDEX idx_thirdparty_cliente_company ON thirdparty.cliente (company_id);
CREATE INDEX idx_thirdparty_cliente_documento_tipo ON thirdparty.cliente (company_id, id_tipo_documento, numero_documento);
CREATE INDEX idx_thirdparty_proveedor_company ON thirdparty.proveedor (company_id);
CREATE INDEX idx_thirdparty_proveedor_documento_tipo ON thirdparty.proveedor (company_id, id_tipo_documento, numero_documento);
