server.port=${SERVER_PORT:${BFF_SERVICE_PORT:8083}}
spring.application.name=bff-service

bff.services.tenant-url=${TENANT_SERVICE_URL:http://localhost:8084}
bff.services.identity-url=${IDENTITY_SERVICE_URL:http://localhost:8092}
bff.services.catalog-url=${CATALOG_SERVICE_URL:http://localhost:8085}
bff.services.thirdparty-url=${THIRDPARTY_SERVICE_URL:http://localhost:8086}
bff.services.inventory-url=${INVENTORY_SERVICE_URL:http://localhost:8087}
bff.services.billing-url=${BILLING_SERVICE_URL:http://localhost:8088}
bff.services.accounting-url=${ACCOUNTING_SERVICE_URL:http://localhost:8090}
bff.services.audit-url=${AUDIT_SERVICE_URL:http://localhost:8091}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
