package com.msvanegasg.facturaelectronica.exception;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    BUSINESS_RULE_VIOLATION,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    UNAUTHORIZED,
    FORBIDDEN,
    TENANT_ACCESS_DENIED,
    EXTERNAL_PROVIDER_ERROR,
    IDEMPOTENCY_CONFLICT,
    INTERNAL_ERROR
}
