CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TABLE catalog.tipodocumento (
    codigo BIGINT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(100),
    activo BOOLEAN NOT NULL
);

CREATE TABLE catalog.categoria (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL
);

CREATE TABLE catalog.producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(250),
    precio_base NUMERIC(38, 2) NOT NULL,
    cantidad_stock INTEGER NOT NULL,
    id_categoria BIGINT NOT NULL,
    activo BOOLEAN NOT NULL,
    codigo_barras BIGINT NOT NULL,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES catalog.categoria (id_categoria)
);

CREATE TABLE catalog.metodo_pago (
    id_metodo_pago BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL
);

CREATE TABLE catalog.tipo_gasto (
    id_tipo_gasto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL
);

CREATE TABLE catalog.pais (
    codigo_pais VARCHAR(10) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    moneda VARCHAR(50),
    activo BOOLEAN NOT NULL
);

CREATE TABLE catalog.impuesto (
    id_impuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    porcentaje NUMERIC(5, 2) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    codigo_pais VARCHAR(10) NOT NULL,
    activo BOOLEAN NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    CONSTRAINT fk_impuesto_pais FOREIGN KEY (codigo_pais) REFERENCES catalog.pais (codigo_pais)
);

CREATE TABLE catalog.parametros (
    id_parametro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID,
    clave VARCHAR(100) NOT NULL,
    valor TEXT NOT NULL,
    descripcion VARCHAR(500),
    activo BOOLEAN NOT NULL,
    CONSTRAINT uk_parametro_clave_company UNIQUE (company_id, clave)
);

CREATE INDEX idx_catalog_categoria_company ON catalog.categoria (company_id);
CREATE INDEX idx_catalog_producto_company ON catalog.producto (company_id);
CREATE INDEX idx_catalog_producto_codigo_barras ON catalog.producto (codigo_barras);
CREATE INDEX idx_catalog_metodo_pago_company ON catalog.metodo_pago (company_id);
CREATE INDEX idx_catalog_tipo_gasto_company ON catalog.tipo_gasto (company_id);
CREATE INDEX idx_catalog_parametros_company ON catalog.parametros (company_id);
