server.port=${SERVER_PORT:${TENANT_SERVICE_PORT:8084}}
spring.application.name=tenant-service

spring.datasource.url=${TENANT_DB_URL:${DB_URL}}
spring.datasource.username=${TENANT_DB_USERNAME:${DB_USERNAME}}
spring.datasource.password=${TENANT_DB_PASSWORD:${DB_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=tenant

spring.flyway.schemas=tenant
spring.flyway.default-schema=tenant
spring.flyway.create-schemas=true

management.endpoints.web.exposure.include=health
