package com.msvanegasg.facturaelectronica.accounting.domain.model;

public enum AccountingEventType {
    SALE_CONFIRMED,
    PURCHASE_CONFIRMED,
    INVENTORY_REPLENISHMENT_CONFIRMED,
    EXPENSE_CONFIRMED,
    OPERATING_EXPENSE_CONFIRMED,
    ASSET_PURCHASE_CONFIRMED,
    ACCOUNT_RECEIVABLE_REGISTERED,
    ACCOUNTS_PAYABLE_PAYMENT_REGISTERED,
    ACCOUNTS_RECEIVABLE_PAYMENT_REGISTERED,
    PAYROLL_DAILY_PAYMENT_REGISTERED,
    CREDIT_NOTE_VALIDATED,
    ADJUSTMENT_CONFIRMED
}
