CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE roles (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL
);

CREATE TABLE usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(50) NOT NULL,
    correo_electronico VARCHAR(100) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    id_rol BIGINT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT fk_usuarios_roles FOREIGN KEY (id_rol) REFERENCES roles (id_rol)
);

CREATE TABLE auditoria (
    id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    descripcion VARCHAR(255),
    accion VARCHAR(100) NOT NULL,
    CONSTRAINT fk_auditoria_usuarios FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario)
);

CREATE TABLE registro_accesos (
    id_registro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT,
    fecha_hora TIMESTAMP,
    direccion_ip VARCHAR(255),
    accion VARCHAR(255),
    detalle VARCHAR(255),
    CONSTRAINT fk_registro_accesos_usuarios FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario)
);

CREATE TABLE tipodocumento (
    codigo BIGINT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(100),
    activo BOOLEAN NOT NULL
);

CREATE TABLE cliente (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    id_tipo_documento BIGINT NOT NULL,
    numero_documento BIGINT NOT NULL UNIQUE,
    digito_verificacion INTEGER,
    direccion VARCHAR(150),
    telefono VARCHAR(15),
    correo_electronico VARCHAR(100),
    tipo_cliente VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL
);

CREATE TABLE proveedor (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    id_tipo_documento BIGINT NOT NULL,
    numero_documento BIGINT NOT NULL UNIQUE,
    digito_verificacion INTEGER,
    direccion VARCHAR(150),
    telefono VARCHAR(15),
    correo_electronico VARCHAR(100),
    activo BOOLEAN NOT NULL,
    CONSTRAINT fk_proveedor_tipodocumento FOREIGN KEY (id_tipo_documento) REFERENCES tipodocumento (codigo)
);

CREATE TABLE categoria (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL
);

CREATE TABLE producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(250),
    precio_base NUMERIC(38, 2) NOT NULL,
    cantidad_stock INTEGER NOT NULL,
    id_categoria BIGINT NOT NULL,
    activo BOOLEAN NOT NULL,
    codigo_barras BIGINT NOT NULL,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES categoria (id_categoria)
);

CREATE TABLE metodo_pago (
    id_metodo_pago BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL
);

CREATE TABLE tipo_gasto (
    id_tipo_gasto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL
);

CREATE TABLE pais (
    codigo_pais VARCHAR(10) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    moneda VARCHAR(50),
    activo BOOLEAN NOT NULL
);

CREATE TABLE impuesto (
    id_impuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    porcentaje NUMERIC(5, 2) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    codigo_pais VARCHAR(10) NOT NULL,
    activo BOOLEAN NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    CONSTRAINT fk_impuesto_pais FOREIGN KEY (codigo_pais) REFERENCES pais (codigo_pais)
);

CREATE TABLE parametros (
    id_parametro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave VARCHAR(100) NOT NULL,
    valor TEXT NOT NULL,
    descripcion VARCHAR(500),
    activo BOOLEAN NOT NULL,
    CONSTRAINT uk_parametro_clave UNIQUE (clave)
);

CREATE TABLE compra (
    id_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    fecha TIMESTAMP,
    subtotal NUMERIC(38, 2),
    iva_total NUMERIC(38, 2),
    total NUMERIC(38, 2),
    url_evidencia VARCHAR(255),
    estado VARCHAR(20) NOT NULL,
    activo BOOLEAN
);

CREATE TABLE detalle_compra (
    id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(38, 2) NOT NULL,
    subtotal NUMERIC(38, 2) NOT NULL,
    iva NUMERIC(38, 2) NOT NULL,
    total_linea NUMERIC(38, 2) NOT NULL,
    activo BOOLEAN NOT NULL,
    CONSTRAINT fk_detalle_compra_compra FOREIGN KEY (id_compra) REFERENCES compra (id_compra)
);

CREATE TABLE gastos (
    id_gasto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    monto NUMERIC(15, 2) NOT NULL,
    descripcion VARCHAR(255),
    id_tipo_gasto BIGINT NOT NULL,
    id_metodo_pago BIGINT NOT NULL,
    url_evidencia VARCHAR(255),
    estado VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL,
    CONSTRAINT fk_gastos_tipo_gasto FOREIGN KEY (id_tipo_gasto) REFERENCES tipo_gasto (id_tipo_gasto),
    CONSTRAINT fk_gastos_metodo_pago FOREIGN KEY (id_metodo_pago) REFERENCES metodo_pago (id_metodo_pago)
);

CREATE TABLE detalle_gasto (
    id_detalle_gasto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_gasto BIGINT,
    cantidad INTEGER,
    descripcion VARCHAR(255),
    monto_unitario NUMERIC(38, 2),
    subtotal NUMERIC(38, 2),
    CONSTRAINT fk_detalle_gasto_gastos FOREIGN KEY (id_gasto) REFERENCES gastos (id_gasto)
);

CREATE TABLE factura (
    id_factura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    id_cliente BIGINT NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    iva_total NUMERIC(12, 2) NOT NULL,
    total NUMERIC(12, 2) NOT NULL,
    metodo_pago BIGINT NOT NULL,
    estado VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL,
    CONSTRAINT fk_factura_cliente FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente),
    CONSTRAINT fk_factura_metodo_pago FOREIGN KEY (metodo_pago) REFERENCES metodo_pago (id_metodo_pago)
);

CREATE TABLE detalle_factura (
    id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_factura BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    iva NUMERIC(12, 2) NOT NULL,
    total_linea NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_detalle_factura_factura FOREIGN KEY (id_factura) REFERENCES factura (id_factura),
    CONSTRAINT fk_detalle_factura_producto FOREIGN KEY (id_producto) REFERENCES producto (id_producto)
);

CREATE INDEX idx_cliente_documento_tipo ON cliente (id_tipo_documento, numero_documento);
CREATE INDEX idx_proveedor_documento_tipo ON proveedor (id_tipo_documento, numero_documento);
CREATE INDEX idx_producto_codigo_barras ON producto (codigo_barras);
CREATE INDEX idx_compra_activo ON compra (activo);
CREATE INDEX idx_factura_estado ON factura (estado);
CREATE INDEX idx_gastos_estado ON gastos (estado);
